
package cs2731.discourse;

/**
 * Represents a discourse role annotation, as generated by the
 * pdtb discourse parser
 *
 * @author conrada@cs.pitt.edu
 */
public class DiscourseAnnotation {

    // is the relation explicit?
    protected boolean isExp;

    // id given to the relation in text
    protected int id;

    // type of discourse relation represented
    protected DiscourseRelType type;

    // text in the arg1 span
    protected String arg1;

    // full sentence in which arg1 appears (optional)
    protected String arg1Sent;

    // index to sentence in which arg1 appears (optional)
    protected int arg1SentIndex;

    // text in the arg2 span
    protected String arg2;

    // full sentence in which arg2 appears (optional)
    protected String arg2Sent;

    // index to sentence in which arg2 appears (optional)
    protected int arg2SentIndex;

    // (if present) text in the conn span
    protected String conn;

    // index to sentence in which conn appears (optional)
    protected int connSentIndex;

    public DiscourseAnnotation(boolean isExp, int id) {
        // other fields will be filled in later
        this.isExp = isExp;
        this.id = id;
    }

    public DiscourseAnnotation(String isExp, int id, DiscourseRelType type) {
        if (isExp.equals("NonExp"))
            this.isExp = false;
        else if (isExp.equals("Exp"))
            this.isExp = true;
        else
            this.isExp = false;
        this.id = id;
        this.type = type;
        conn = "";
        arg1 = "";
        arg2 = "";
    }

    public int getArg1SentIndex() {
        return arg1SentIndex;
    }

    public void setArg1SentIndex(int arg1SentIndex) {
        this.arg1SentIndex = arg1SentIndex;
    }

    public int getArg2SentIndex() {
        return arg2SentIndex;
    }

    public void setArg2SentIndex(int arg2SentIndex) {
        this.arg2SentIndex = arg2SentIndex;
    }

    public int getConnSentIndex() {
        return connSentIndex;
    }

    public void setConnSentIndex(int connSentIndex) {
        this.connSentIndex = connSentIndex;
    }

    public String getArg1() {
        return arg1;
    }

    public String getArg1Sent() {
        return arg1Sent;
    }

    public String getArg2() {
        return arg2;
    }

    public String getArg2Sent() {
        return arg2Sent;
    }

    public String getConn() {
        return conn;
    }

    public int getId() {
        return id;
    }

    public boolean isIsExp() {
        return isExp;
    }

    public DiscourseRelType getType() {
        return type;
    }

    public void setArg1(String arg1) {
        this.arg1 = arg1;
    }

    public void setArg1Sent(String arg1Sent) {
        this.arg1Sent = arg1Sent;
    }

    public void setArg2(String arg2) {
        this.arg2 = arg2;
    }

    public void setArg2Sent(String arg2Sent) {
        this.arg2Sent = arg2Sent;
    }

    public void setConn(String conn) {
        this.conn = conn;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setIsExp(boolean isExp) {
        this.isExp = isExp;
    }

    public void setIsExp(String isExp) {
        if (isExp.equals("NonExp"))
            this.isExp = false;
        else if (isExp.equals("Exp"))
            this.isExp = true;
        else
            this.isExp = false;
    }

    public void setType(DiscourseRelType type) {
        this.type = type;
    }

    @Override
    public String toString() {
        return "DiscourseAnnotation{" + "isExp=" + isExp + ", id=" + id + ", type=" + type + ", arg1=" + arg1 + ", arg1Sent=" + arg1Sent + ", arg2=" + arg2 + ", arg2Sent=" + arg2Sent + ", conn=" + conn + '}';
    }

    
}
